project:
  type: book

book:
  title: "Purr Palace Cookbook"
  subtitle: "Culinary Treasures Revealed"
  author: "Randi Bolt and Tanner Heffner"
  date: "7-6-2023"
  chapters:
    - index.qmd
    - part: chapters/breakfasts/breakfasts.qmd
      chapters: 
        - chapters/breakfasts/omurice.qmd
        - chapters/breakfasts/savory-toast.qmd
    - part: chapters/snacks/snacks.qmd
      chapters: 
        - chapters/snacks/hummus.qmd
    - part: chapters/desserts/desserts.qmd
      chapters: 
        - chapters/desserts/cherry-hand-pies.qmd
        - chapters/desserts/chocolate_chip_cookies.qmd
        - chapters/desserts/spritz_cookies.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



